# Generated by Django 3.1.1 on 2020-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consoleName', models.CharField(max_length=50)),
                ('fabricante', models.CharField(max_length=50)),
                ('lancamento', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
